import type { CompanyProfile } from "../schema/types.ts";

export const syntheticCompanyProfiles: CompanyProfile[] = [
  {
    id: "synthetic_series_a_50",
    label: "50-person Series A synthetic startup",
    advancedEnabled: false,
    companyContext: {
      company_size_band: "31-50",
      funding_stage: "series_a",
      has_hr_owner: true,
      has_level_system: false,
      has_salary_band: false,
      has_performance_review: true,
      has_variable_pay: false,
      has_equity_plan: true,
      current_ai_tooling_level: "ad_hoc",
    },
    compensationSnapshot: {
      total_headcount: 50,
      total_monthly_base_pay: 302000000,
      total_monthly_fixed_allowance: 10500000,
      average_salary_by_level: {
        L1: 42000000,
        L2: 61000000,
        L3: 82000000,
        L4: 112000000,
      },
      headcount_by_level: {
        L1: 18,
        L2: 20,
        L3: 10,
        L4: 2,
      },
      headcount_by_function: {
        engineering: 25,
        sales: 10,
        operations: 8,
        people: 3,
        product: 4,
      },
      recent_raise_budget: 96000000,
      exception_raise_frequency: "rare",
      counteroffer_frequency: "rare",
      new_hire_premium_exists: true,
      pay_inversion_case_count: 2,
      out_of_band_case_count: 0,
      undocumented_negotiation_level: "low",
      variable_pay_linked_to_performance: false,
      manager_can_explain_pay_basis: false,
    },
    hiringPlan: {
      planned_hires_6m: {
        L1: 3,
        L2: 4,
        L3: 1,
      },
      planned_hires_12m: {
        L1: 6,
        L2: 7,
        L3: 2,
      },
      average_expected_salary_by_level: {
        L1: 46000000,
        L2: 67000000,
        L3: 88000000,
      },
      hiring_freeze_toggle: false,
    },
  },
  {
    id: "synthetic_series_b_90",
    label: "90-person Series B synthetic startup",
    advancedEnabled: false,
    companyContext: {
      company_size_band: "51-100",
      funding_stage: "series_b",
      has_hr_owner: true,
      has_level_system: true,
      has_salary_band: true,
      has_performance_review: true,
      has_variable_pay: true,
      has_equity_plan: true,
      current_ai_tooling_level: "team_level",
    },
    compensationSnapshot: {
      total_headcount: 90,
      total_monthly_base_pay: 615000000,
      total_monthly_fixed_allowance: 24000000,
      total_expected_variable_pay: 210000000,
      average_salary_by_level: {
        L1: 45000000,
        L2: 64000000,
        L3: 85000000,
        L4: 118000000,
      },
      headcount_by_level: {
        L1: 24,
        L2: 34,
        L3: 24,
        L4: 8,
      },
      headcount_by_function: {
        engineering: 42,
        sales: 19,
        operations: 11,
        product: 10,
        people: 8,
      },
      recent_raise_budget: 185000000,
      exception_raise_frequency: "occasional",
      counteroffer_frequency: "rare",
      new_hire_premium_exists: true,
      pay_inversion_case_count: 4,
      out_of_band_case_count: 3,
      undocumented_negotiation_level: "medium",
      variable_pay_linked_to_performance: true,
      manager_can_explain_pay_basis: true,
    },
    hiringPlan: {
      planned_hires_6m: {
        L1: 4,
        L2: 5,
        L3: 3,
        L4: 1,
      },
      planned_hires_12m: {
        L1: 8,
        L2: 9,
        L3: 5,
        L4: 2,
      },
      average_expected_salary_by_level: {
        L1: 50000000,
        L2: 71000000,
        L3: 92000000,
        L4: 126000000,
      },
      hiring_freeze_toggle: false,
      optional_cash_balance: 4100000000,
      optional_runway_months: 14.5,
    },
    salaryBands: [
      {
        level: "L1",
        min: 38000000,
        midpoint: 46000000,
        max: 55000000,
        range_spread: 37.0,
        midpoint_progression: 0,
      },
      {
        level: "L2",
        min: 54000000,
        midpoint: 66000000,
        max: 78000000,
        range_spread: 36.4,
        midpoint_progression: 43.5,
      },
      {
        level: "L3",
        min: 72000000,
        midpoint: 88000000,
        max: 104000000,
        range_spread: 36.4,
        midpoint_progression: 33.3,
      },
      {
        level: "L4",
        min: 98000000,
        midpoint: 118000000,
        max: 142000000,
        range_spread: 37.3,
        midpoint_progression: 34.1,
      },
    ],
  },
  {
    id: "synthetic_growth_130_exception_debt",
    label: "130-person growth-stage synthetic startup with exception debt",
    advancedEnabled: false,
    companyContext: {
      company_size_band: "101-300",
      funding_stage: "series_b",
      has_hr_owner: true,
      has_level_system: true,
      has_salary_band: false,
      has_performance_review: true,
      has_variable_pay: true,
      has_equity_plan: true,
      current_ai_tooling_level: "team_level",
    },
    compensationSnapshot: {
      total_headcount: 130,
      total_monthly_base_pay: 968000000,
      total_monthly_fixed_allowance: 39000000,
      total_expected_variable_pay: 360000000,
      average_salary_by_level: {
        L1: 48000000,
        L2: 70000000,
        L3: 94000000,
        L4: 132000000,
        L5: 168000000,
      },
      headcount_by_level: {
        L1: 34,
        L2: 50,
        L3: 32,
        L4: 12,
        L5: 2,
      },
      headcount_by_function: {
        engineering: 60,
        sales: 28,
        operations: 17,
        product: 15,
        people: 10,
      },
      recent_raise_budget: 310000000,
      exception_raise_frequency: "frequent",
      counteroffer_frequency: "frequent",
      new_hire_premium_exists: true,
      pay_inversion_case_count: 14,
      out_of_band_case_count: 18,
      undocumented_negotiation_level: "high",
      variable_pay_linked_to_performance: false,
      manager_can_explain_pay_basis: false,
    },
    hiringPlan: {
      planned_hires_6m: {
        L1: 6,
        L2: 8,
        L3: 5,
        L4: 2,
      },
      planned_hires_12m: {
        L1: 12,
        L2: 15,
        L3: 9,
        L4: 4,
      },
      average_expected_salary_by_level: {
        L1: 53000000,
        L2: 79000000,
        L3: 106000000,
        L4: 145000000,
      },
      hiring_freeze_toggle: false,
    },
  },
  {
    id: "synthetic_advanced_ai_inputs",
    label: "Advanced AI tooling synthetic scenario sample",
    advancedEnabled: true,
    companyContext: {
      company_size_band: "51-100",
      funding_stage: "series_a",
      has_hr_owner: true,
      has_level_system: true,
      has_salary_band: true,
      has_performance_review: true,
      has_variable_pay: false,
      has_equity_plan: true,
      current_ai_tooling_level: "company_standard",
    },
    compensationSnapshot: {
      total_headcount: 76,
      total_monthly_base_pay: 532000000,
      total_monthly_fixed_allowance: 20500000,
      average_salary_by_level: {
        L1: 47000000,
        L2: 66000000,
        L3: 91000000,
        L4: 124000000,
      },
      headcount_by_level: {
        L1: 20,
        L2: 28,
        L3: 21,
        L4: 7,
      },
      headcount_by_function: {
        engineering: 36,
        sales: 14,
        operations: 9,
        product: 10,
        people: 7,
      },
      recent_raise_budget: 150000000,
      exception_raise_frequency: "occasional",
      counteroffer_frequency: "occasional",
      new_hire_premium_exists: true,
      pay_inversion_case_count: 5,
      out_of_band_case_count: 4,
      undocumented_negotiation_level: "medium",
      variable_pay_linked_to_performance: false,
      manager_can_explain_pay_basis: true,
    },
    hiringPlan: {
      planned_hires_6m: {
        L1: 5,
        L2: 4,
        L3: 2,
      },
      planned_hires_12m: {
        L1: 9,
        L2: 8,
        L3: 4,
      },
      average_expected_salary_by_level: {
        L1: 52000000,
        L2: 74000000,
        L3: 98000000,
      },
      hiring_freeze_toggle: true,
      optional_runway_months: 12,
    },
    salaryBands: [
      {
        level: "L1",
        min: 40000000,
        midpoint: 48000000,
        max: 58000000,
        range_spread: 37.5,
        midpoint_progression: 0,
      },
      {
        level: "L2",
        min: 56000000,
        midpoint: 68000000,
        max: 82000000,
        range_spread: 38.2,
        midpoint_progression: 41.7,
      },
      {
        level: "L3",
        min: 78000000,
        midpoint: 94000000,
        max: 114000000,
        range_spread: 38.3,
        midpoint_progression: 38.2,
      },
      {
        level: "L4",
        min: 104000000,
        midpoint: 126000000,
        max: 152000000,
        range_spread: 38.1,
        midpoint_progression: 34.0,
      },
    ],
    aiScenarioInputs: {
      planned_ai_tool_budget_monthly: 4500000,
      planned_ai_tool_budget_annual: 54000000,
      hiring_delay_months: 6,
      affected_roles_or_functions: ["engineering", "operations"],
      productivity_leakage_questions: {
        saved_time_reinvested_into_team_output: "no",
        workflow_owner_defined: "no",
        manager_reviews_output_change: "unknown",
      },
      junior_pipeline_risk_questions: {
        junior_hiring_paused: "yes",
        mentoring_capacity_preserved: "unknown",
      },
      orchestrator_target_count: 4,
      premium_pool_allocation_rate: 3,
    },
  },
];
