export const FORBIDDEN_FOUNDER_TERMS = [
  "finding",
  "theme",
  "relationship",
  "shadow band",
  "pay inversion",
  "loyalty tax",
  "level fiction",
  "cohort",
  "defensibility",
  "replay",
  "correction floor",
  "exposure",
  "severity",
  "confidence",
  "normalized row",
  "raw data",
  "PII",
  "stale",
  "memo",
  "decision domain",
  "AI substitution",
  "job replacement",
  "Total Work Cost",
  "attrition probability",
  "salary calculator",
  "이직 확률",
  "생산성 향상률",
  "대체율",
] as const;
