export const FORBIDDEN_FOUNDER_TERMS = [
  "finding",
  "theme",
  "relationship",
  "shadow band",
  "pay inversion",
  "loyalty tax",
  "level fiction",
  "cohort",
  "defensibility",
  "replay",
  "correction floor",
  "exposure",
  "severity",
  "confidence",
  "normalized row",
  "raw data",
  "PII",
  "stale",
  "memo",
  "decision domain",
] as const;
